services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1704
      POSTGRES_DB: YoUniverseDemo
    volumes:
      - pgdata:/var/lib/postgresql/
volumes:
  pgdata:
